"""empty message

Revision ID: adc71611dfae
Revises: 5a9562895ca9
Create Date: 2021-04-25 15:39:05.161599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc71611dfae'
down_revision = '5a9562895ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('set', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
