"""empty message

Revision ID: faae1560db39
Revises: adc71611dfae
Create Date: 2021-04-25 16:18:45.181378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faae1560db39'
down_revision = 'adc71611dfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
